name: PRChangedCalled2
run-name: "${{ github.workflow }}-${{ github.event.label.name }}-${{ github.event.number }}"
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'

env:
  REPO:            ${{ github.repository }}
  REPO_DIR:        ${{ github.workspace }}/${{ github.event.repository.name }}
  REPO_ORG:        ${{ github.event.repository.owner.login }}
  PR_NUMBER:       ${{ github.event.number }}
  BASE_BRANCH:     ${{ github.event.pull_request.base.ref }}
  WORKFLOW_NAME:   ${{ github.workflow }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}
  SCRIPT_DIR:      ${{ github.workspace }}/asterisk-ci-actions/scripts
  GH_TOKEN:        ${{ github.token }}
  LOG_DIR:         ${{ github.workspace }}/logs
  ACTIONS_OWNER:   asterisk
  ACTIONS_REPO:    asterisk-ci-actions
  ACTIONS_BRANCH:  main

jobs:
  Cleanup2:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: |
          gh pr comment --repo ${REPO} ${PR_NUMBER} --body "This is a comment from ${WORKFLOW_NAME}" || \
            echo "Add comment failed.  Expected"
          mkdir cacheit
          ls -al > cacheit/dirlist.txt
          mkdir output
          ls -al > output/dirlist2.txt
          echo "XXX${{ secrets.SOME_SECRET }}XXX" > output/test.out
          echo "VVV${{ vars.SOME_VARIABLE }}VVV" >> output/test.out

#      - id: cache-build-output
#        name: CacheBuildProducts
#        uses: actions/cache/save@v4
#        with:
#          path: cacheit
#          key:  Cleanup2-${{ env.PR_NUMBER }}

      - name: Save Output
        if: always()
        id: save-output
        uses: actions/upload-artifact@v4
        with:
          name: Cleanup2-${{ env.PR_NUMBER }}
          if-no-files-found: ignore
          path: output


